FROM node:carbon

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
RUN npm install
RUN npm install -g @ampretia/composer-wallet-ibmcos
ENV NODE_CONFIG '{"composer": {"wallet": {"type": "@ampretia/composer-wallet-ibmcos","desc": "Uses the IBM Cloud Object Store","options": {"bucketName": "commercial-paper-demo",                "endpoint": "s3-api.us-geo.objectstorage.softlayer.net",                "apikey": "WmKck6Ta6JAaqM57mfkD_8kGDkldfJ4zfSTl-Id5oqhx",                "serviceInstanceId": "crn:v1:bluemix:public:cloud-object-storage:global:a/f312377c857f745dd4741a70d09a8e4c:fb474f32-8d51-4864-a2e7-459105254cfd::"            }        }    }}'
COPY . . 

EXPOSE 3000
CMD ["npm","start"]